/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.springkafkaavro.order.event.avro;
@org.apache.avro.specific.AvroGenerated
public enum OrderStatusAvro implements org.apache.avro.generic.GenericEnumSymbol<OrderStatusAvro> {
  ORDERED, REFUND, DELIVERED, CANCELED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderStatusAvro\",\"namespace\":\"com.example.springkafkaavro.order.event.avro\",\"symbols\":[\"ORDERED\",\"REFUND\",\"DELIVERED\",\"CANCELED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
