/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.springkafkaavro.common.kafka.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderCancelKafkaEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7774852464477535531L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderCancelKafkaEvent\",\"namespace\":\"com.example.springkafkaavro.common.kafka.model\",\"fields\":[{\"name\":\"odrderId\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderCancelKafkaEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderCancelKafkaEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderCancelKafkaEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderCancelKafkaEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderCancelKafkaEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderCancelKafkaEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderCancelKafkaEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderCancelKafkaEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderCancelKafkaEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long odrderId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderCancelKafkaEvent() {}

  /**
   * All-args constructor.
   * @param odrderId The new value for odrderId
   */
  public OrderCancelKafkaEvent(java.lang.Long odrderId) {
    this.odrderId = odrderId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return odrderId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: odrderId = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'odrderId' field.
   * @return The value of the 'odrderId' field.
   */
  public long getOdrderId() {
    return odrderId;
  }


  /**
   * Sets the value of the 'odrderId' field.
   * @param value the value to set.
   */
  public void setOdrderId(long value) {
    this.odrderId = value;
  }

  /**
   * Creates a new OrderCancelKafkaEvent RecordBuilder.
   * @return A new OrderCancelKafkaEvent RecordBuilder
   */
  public static com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder newBuilder() {
    return new com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder();
  }

  /**
   * Creates a new OrderCancelKafkaEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderCancelKafkaEvent RecordBuilder
   */
  public static com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder newBuilder(com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder other) {
    if (other == null) {
      return new com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder();
    } else {
      return new com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder(other);
    }
  }

  /**
   * Creates a new OrderCancelKafkaEvent RecordBuilder by copying an existing OrderCancelKafkaEvent instance.
   * @param other The existing instance to copy.
   * @return A new OrderCancelKafkaEvent RecordBuilder
   */
  public static com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder newBuilder(com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent other) {
    if (other == null) {
      return new com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder();
    } else {
      return new com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderCancelKafkaEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderCancelKafkaEvent>
    implements org.apache.avro.data.RecordBuilder<OrderCancelKafkaEvent> {

    private long odrderId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.odrderId)) {
        this.odrderId = data().deepCopy(fields()[0].schema(), other.odrderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderCancelKafkaEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.odrderId)) {
        this.odrderId = data().deepCopy(fields()[0].schema(), other.odrderId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'odrderId' field.
      * @return The value.
      */
    public long getOdrderId() {
      return odrderId;
    }


    /**
      * Sets the value of the 'odrderId' field.
      * @param value The value of 'odrderId'.
      * @return This builder.
      */
    public com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder setOdrderId(long value) {
      validate(fields()[0], value);
      this.odrderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'odrderId' field has been set.
      * @return True if the 'odrderId' field has been set, false otherwise.
      */
    public boolean hasOdrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'odrderId' field.
      * @return This builder.
      */
    public com.example.springkafkaavro.common.kafka.model.OrderCancelKafkaEvent.Builder clearOdrderId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderCancelKafkaEvent build() {
      try {
        OrderCancelKafkaEvent record = new OrderCancelKafkaEvent();
        record.odrderId = fieldSetFlags()[0] ? this.odrderId : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderCancelKafkaEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderCancelKafkaEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderCancelKafkaEvent>
    READER$ = (org.apache.avro.io.DatumReader<OrderCancelKafkaEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.odrderId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.odrderId = in.readLong();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.odrderId = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










